// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/PassManager.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Analysis/Verifier.h>
#include <llvm/Assembly/PrintModulePass.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>
#include <algorithm>
using namespace llvm;

Module* makeLLVMModule();

int main(int argc, char**argv) {
  Module* Mod = makeLLVMModule();
  verifyModule(*Mod, PrintMessageAction);
  PassManager PM;
  PM.add(createPrintModulePass(&outs()));
  PM.run(*Mod);
  return 0;
}


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("example1.bc", getGlobalContext());
 mod->setDataLayout("e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128");
 mod->setTargetTriple("x86_64-unknown-linux-gnu");
 
 // Type Definitions
 ArrayType* ArrayTy_0 = ArrayType::get(IntegerType::get(mod->getContext(), 8), 16);
 
 PointerType* PointerTy_1 = PointerType::get(ArrayTy_0, 0);
 
 std::vector<Type*>FuncTy_2_args;
 FunctionType* FuncTy_2 = FunctionType::get(
  /*Result=*/Type::getVoidTy(mod->getContext()),
  /*Params=*/FuncTy_2_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_3 = PointerType::get(FuncTy_2, 0);
 
 std::vector<Type*>FuncTy_4_args;
 FuncTy_4_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_4 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_4_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_5 = PointerType::get(IntegerType::get(mod->getContext(), 32), 0);
 
 std::vector<Type*>FuncTy_6_args;
 FunctionType* FuncTy_6 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_6_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_7 = PointerType::get(FuncTy_4, 0);
 
 PointerType* PointerTy_8 = PointerType::get(IntegerType::get(mod->getContext(), 8), 0);
 
 std::vector<Type*>FuncTy_10_args;
 FuncTy_10_args.push_back(PointerTy_8);
 FunctionType* FuncTy_10 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_10_args,
  /*isVarArg=*/true);
 
 PointerType* PointerTy_9 = PointerType::get(FuncTy_10, 0);
 
 
 // Function Declarations
 
 Function* func_pop_direct_branch = mod->getFunction("pop_direct_branch");
 if (!func_pop_direct_branch) {
 func_pop_direct_branch = Function::Create(
  /*Type=*/FuncTy_2,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"pop_direct_branch", mod); 
 func_pop_direct_branch->setCallingConv(CallingConv::C);
 }
 AttributeSet func_pop_direct_branch_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_pop_direct_branch_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_pop_direct_branch->setAttributes(func_pop_direct_branch_PAL);
 
 Function* func_pow2 = mod->getFunction("pow2");
 if (!func_pow2) {
 func_pow2 = Function::Create(
  /*Type=*/FuncTy_4,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"pow2", mod); 
 func_pow2->setCallingConv(CallingConv::C);
 }
 AttributeSet func_pow2_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_pow2_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_pow2->setAttributes(func_pow2_PAL);
 
 Function* func_main = mod->getFunction("main");
 if (!func_main) {
 func_main = Function::Create(
  /*Type=*/FuncTy_6,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"main", mod); 
 func_main->setCallingConv(CallingConv::C);
 }
 AttributeSet func_main_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_main_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_main->setAttributes(func_main_PAL);
 
 Function* func_printf = mod->getFunction("printf");
 if (!func_printf) {
 func_printf = Function::Create(
  /*Type=*/FuncTy_10,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"printf", mod); // (external, no body)
 func_printf->setCallingConv(CallingConv::C);
 }
 AttributeSet func_printf_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_printf_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_printf->setAttributes(func_printf_PAL);
 
 // Global Variable Declarations

 
 GlobalVariable* gvar_array__str = new GlobalVariable(/*Module=*/*mod, 
 /*Type=*/ArrayTy_0,
 /*isConstant=*/true,
 /*Linkage=*/GlobalValue::PrivateLinkage,
 /*Initializer=*/0, // has initializer, specified below
 /*Name=*/".str");
 gvar_array__str->setAlignment(1);
 
 // Constant Definitions
 Constant *const_array_11 = ConstantDataArray::getString(mod->getContext(), "pow2 of A = %d\x0A", true);
 ConstantInt* const_int32_12 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
 ConstantInt* const_int32_13 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("0"), 10));
 ConstantInt* const_int32_14 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("10"), 10));
 std::vector<Constant*> const_ptr_15_indices;
 const_ptr_15_indices.push_back(const_int32_13);
 const_ptr_15_indices.push_back(const_int32_13);
 Constant* const_ptr_15 = ConstantExpr::getGetElementPtr(gvar_array__str, const_ptr_15_indices);
 
 // Global Variable Definitions
 gvar_array__str->setInitializer(const_array_11);
 
 // Function Definitions
 
 // Function: pop_direct_branch (func_pop_direct_branch)
 {
  
  BasicBlock* label_16 = BasicBlock::Create(mod->getContext(), "",func_pop_direct_branch,0);
  
  // Block  (label_16)
  InlineAsm* ptr_18 = InlineAsm::get(FuncTy_2, "popq %rbp
	addq $$8, %rsp
	leave
	movq (%rsp), %rax
	addq $$8, %rsp
	jmp *%rax
	", "~{dirflag},~{fpsr},~{flags}",true);
  CallInst* void_17 = CallInst::Create(ptr_18, "", label_16);
  void_17->setCallingConv(CallingConv::C);
  void_17->setTailCall(false);
  AttributeSet void_17_PAL;
  {
   SmallVector<AttributeSet, 4> Attrs;
   AttributeSet PAS;
    {
     AttrBuilder B;
     B.addAttribute(Attribute::NoUnwind);
     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
    }
   
   Attrs.push_back(PAS);
   void_17_PAL = AttributeSet::get(mod->getContext(), Attrs);
   
  }
  void_17->setAttributes(void_17_PAL);
  
  ReturnInst::Create(mod->getContext(), label_16);
  
 }
 
 // Function: pow2 (func_pow2)
 {
  Function::arg_iterator args = func_pow2->arg_begin();
  Value* int32_x = args++;
  int32_x->setName("x");
  
  BasicBlock* label_20 = BasicBlock::Create(mod->getContext(), "",func_pow2,0);
  
  // Block  (label_20)
  AllocaInst* ptr_21 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "", label_20);
  ptr_21->setAlignment(4);
  StoreInst* void_22 = new StoreInst(int32_x, ptr_21, false, label_20);
  void_22->setAlignment(4);
  LoadInst* int32_23 = new LoadInst(ptr_21, "", false, label_20);
  int32_23->setAlignment(4);
  LoadInst* int32_24 = new LoadInst(ptr_21, "", false, label_20);
  int32_24->setAlignment(4);
  BinaryOperator* int32_25 = BinaryOperator::Create(Instruction::Mul, int32_23, int32_24, "", label_20);
  ReturnInst::Create(mod->getContext(), int32_25, label_20);
  
 }
 
 // Function: main (func_main)
 {
  
  BasicBlock* label_27 = BasicBlock::Create(mod->getContext(), "",func_main,0);
  
  // Block  (label_27)
  AllocaInst* ptr_28 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "", label_27);
  ptr_28->setAlignment(4);
  AllocaInst* ptr_a = new AllocaInst(IntegerType::get(mod->getContext(), 32), "a", label_27);
  ptr_a->setAlignment(4);
  AllocaInst* ptr_p = new AllocaInst(IntegerType::get(mod->getContext(), 32), "p", label_27);
  ptr_p->setAlignment(4);
  StoreInst* void_29 = new StoreInst(const_int32_13, ptr_28, false, label_27);
  StoreInst* void_30 = new StoreInst(const_int32_14, ptr_a, false, label_27);
  void_30->setAlignment(4);
  LoadInst* int32_31 = new LoadInst(ptr_a, "", false, label_27);
  int32_31->setAlignment(4);
  CallInst* int32_32 = CallInst::Create(func_pow2, int32_31, "", label_27);
  int32_32->setCallingConv(CallingConv::C);
  int32_32->setTailCall(false);
  AttributeSet int32_32_PAL;
  int32_32->setAttributes(int32_32_PAL);
  
  StoreInst* void_33 = new StoreInst(int32_32, ptr_p, false, label_27);
  void_33->setAlignment(4);
  LoadInst* int32_34 = new LoadInst(ptr_p, "", false, label_27);
  int32_34->setAlignment(4);
  std::vector<Value*> int32_35_params;
  int32_35_params.push_back(const_ptr_15);
  int32_35_params.push_back(int32_34);
  CallInst* int32_35 = CallInst::Create(func_printf, int32_35_params, "", label_27);
  int32_35->setCallingConv(CallingConv::C);
  int32_35->setTailCall(false);
  AttributeSet int32_35_PAL;
  int32_35->setAttributes(int32_35_PAL);
  
  ReturnInst::Create(mod->getContext(), const_int32_13, label_27);
  
 }
 
 return mod;
}
