##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
#DIRS=Scratch
DIRS=Hello
DIRS=P_clone

include $(LEVEL)/Makefile.common
